/* eslint-disable @typescript-eslint/no-unsafe-assignment */

/* eslint-disable @typescript-eslint/no-unsafe-return */

/* eslint-disable @typescript-eslint/no-var-requires */
// CAUTION: this file is automatically generated, do not edit it.
import * as React from 'react';

import { createBottomTabNavigator } from '@react-navigation/bottom-tabs';

import * as route from './routes';

import { BottomTabBar } from '../components';
import { BottomTabsCalendar } from '../screens/BottomTabs/Calendar';
import { BottomTabsHome } from '../screens/BottomTabs/Home';
import { BottomTabsMyPlans } from '../screens/BottomTabs/MyPlans';
import { BottomTabsProfile } from '../screens/BottomTabs/Profile';

const BottomTabsBottomTab = createBottomTabNavigator();

const BottomTabsNavigator = () => {
  return (
    <BottomTabsBottomTab.Navigator
      screenOptions={{
        headerShown: false,
        lazy: true,
      }}
      tabBar={(props) => <BottomTabBar {...props} />}
    >
      <BottomTabsBottomTab.Screen
        name={route.routeBottomTabsHome}
        initialParams={{
          meta: {
            presentation: 'card',
          },
        }}
        component={BottomTabsHome}
      />
      <BottomTabsBottomTab.Screen
        name={route.routeBottomTabsCalendar}
        initialParams={{
          meta: {
            presentation: 'card',
          },
        }}
        component={BottomTabsCalendar}
      />
      <BottomTabsBottomTab.Screen
        name={route.routeBottomTabsMyPlans}
        initialParams={{
          meta: {
            presentation: 'card',
          },
        }}
        component={BottomTabsMyPlans}
      />
      <BottomTabsBottomTab.Screen
        name={route.routeBottomTabsProfile}
        initialParams={{
          meta: {
            presentation: 'card',
          },
        }}
        component={BottomTabsProfile}
      />
    </BottomTabsBottomTab.Navigator>
  );
};
