# yaml-language-server: $schema=../../core/navigation/navigation.schema.json

aliases:
  - &hideHeader
    headerShown: false
  - &lazy
    lazy: true
  - &modal
    presentation: "'modal'"

navigatorsImports:
  BottomTabBar: ../components

navigators:
  BottomTabs:
    type: bottom-tab
    path: ../screens/BottomTabs
    lazy: false
    props:
      screenOptions:
        << : [*hideHeader, *lazy]
      tabBar: props => <BottomTabBar {...props} />
    children:
      - Home
      - Calendar
      - MyPlans
      - Profile










