/* eslint-disable @typescript-eslint/no-unsafe-assignment */

/* eslint-disable @typescript-eslint/no-unsafe-return */

/* eslint-disable @typescript-eslint/no-var-requires */
// CAUTION: this file is automatically generated, do not edit it.
export const routeBottomTabsHome = '/bottom-tabs/home';
export const routeBottomTabsCalendar = '/bottom-tabs/calendar';
export const routeBottomTabsMyPlans = '/bottom-tabs/my-plans';
export const routeBottomTabsProfile = '/bottom-tabs/profile';
export const toBottomTabsHome = [routeBottomTabsNavigator, routeBottomTabsHome] as unknown as Route;
export const toBottomTabsCalendar = [routeBottomTabsNavigator, routeBottomTabsCalendar] as unknown as Route;
export const toBottomTabsMyPlans = [routeBottomTabsNavigator, routeBottomTabsMyPlans] as unknown as Route;
export const toBottomTabsProfile = [routeBottomTabsNavigator, routeBottomTabsProfile] as unknown as Route;
