/* eslint-disable @typescript-eslint/no-unsafe-assignment */

/* eslint-disable @typescript-eslint/no-unsafe-return */

/* eslint-disable @typescript-eslint/no-var-requires */
// CAUTION: this file is automatically generated, do not edit it.
import * as React from 'react';

import { createBottomTabNavigator } from '@react-navigation/bottom-tabs';
import { createNativeStackNavigator } from '@react-navigation/native-stack';

import * as route from './routes';

import { BottomTabBar } from '../components';
import { BottomTabsCalendar } from '../screens/BottomTabs/Calendar';
import { BottomTabsHome } from '../screens/BottomTabs/Home';
import { BottomTabsMyPlans } from '../screens/BottomTabs/MyPlans';
import { BottomTabsProfile } from '../screens/BottomTabs/Profile';
import { BottomTabsTrainerTrainees } from '../screens/BottomTabs/TrainerTrainees';

const BottomTabsBottomTab = createBottomTabNavigator();
const SearchTrainersNativeStack = createNativeStackNavigator();
const AccountNativeStack = createNativeStackNavigator();
const ActivatedUserNativeStack = createNativeStackNavigator();

const BottomTabsNavigator = () => {
  return (
    <BottomTabsBottomTab.Navigator
      screenOptions={{
        headerShown: false,
        lazy: true,
      }}
      tabBar={(props) => <BottomTabBar {...props} />}
    >
      <BottomTabsBottomTab.Screen
        name={route.routeBottomTabsHome}
        initialParams={{
          meta: {
            presentation: 'card',
          },
        }}
        component={BottomTabsHome}
      />
      <BottomTabsBottomTab.Screen
        name={route.routeBottomTabsCalendar}
        initialParams={{
          meta: {
            presentation: 'card',
          },
        }}
        component={BottomTabsCalendar}
      />
      <BottomTabsBottomTab.Screen
        name={route.routeBottomTabsMyPlans}
        initialParams={{
          meta: {
            presentation: 'card',
          },
        }}
        component={BottomTabsMyPlans}
      />
      <BottomTabsBottomTab.Screen
        name={route.routeBottomTabsTrainerTrainees}
        initialParams={{
          meta: {
            presentation: 'card',
          },
        }}
        component={BottomTabsTrainerTrainees}
      />
      <BottomTabsBottomTab.Screen
        name={route.routeBottomTabsProfile}
        initialParams={{
          meta: {
            presentation: 'card',
          },
        }}
        component={BottomTabsProfile}
      />
    </BottomTabsBottomTab.Navigator>
  );
};

const SearchTrainersNavigator = () => {
  return (
    <SearchTrainersNativeStack.Navigator
      screenOptions={{
        headerShown: false,
      }}
    >
      <SearchTrainersNativeStack.Screen
        name={route.routeSearchTrainersList}
        initialParams={{
          meta: {
            presentation: 'card',
          },
        }}
        getComponent={() => require('../screens/SearchTrainers/List').SearchTrainersList}
      />
      <SearchTrainersNativeStack.Screen
        options={{
          presentation: 'modal',
        }}
        name={route.routeSearchTrainersFilters}
        initialParams={{
          meta: {
            presentation: 'modal',
          },
        }}
        getComponent={() => require('../screens/SearchTrainers/Filters').SearchTrainersFilters}
      />
    </SearchTrainersNativeStack.Navigator>
  );
};

const AccountNavigator = () => {
  return (
    <AccountNativeStack.Navigator
      screenOptions={{
        headerShown: false,
      }}
    >
      <AccountNativeStack.Screen
        name={route.routeAccountSettings}
        initialParams={{
          meta: {
            presentation: 'card',
          },
        }}
        getComponent={() => require('../screens/Account/Settings').AccountSettings}
      />
    </AccountNativeStack.Navigator>
  );
};

export const ActivatedUserNavigator = () => {
  return (
    <ActivatedUserNativeStack.Navigator
      screenOptions={{
        headerShown: false,
      }}
    >
      <ActivatedUserNativeStack.Screen
        name={route.routeBottomTabsNavigator}
        initialParams={{
          meta: {
            presentation: 'card',
          },
        }}
        component={BottomTabsNavigator}
      />
      <ActivatedUserNativeStack.Screen
        name={route.routeAccountNavigator}
        initialParams={{
          meta: {
            presentation: 'card',
          },
        }}
        component={AccountNavigator}
      />
      <ActivatedUserNativeStack.Screen
        name={route.routeSearchTrainersNavigator}
        initialParams={{
          meta: {
            presentation: 'card',
          },
        }}
        component={SearchTrainersNavigator}
      />
    </ActivatedUserNativeStack.Navigator>
  );
};
