# yaml-language-server: $schema=../../core/navigation/navigation.schema.json
aliases:
  - &hideHeader
    headerShown: false
  - &lazy
    lazy: true
  - &modal
    presentation: "'modal'"


navigatorsImports:
  BottomTabBar: ../components

navigators:
  BottomTabs:
    type: bottom-tab
    path: ../screens/BottomTabs
    lazy: false
    props:
      screenOptions:
        << : [*hideHeader, *lazy]
      tabBar: props => <BottomTabBar {...props} />
    children:
      - Home
      - Calendar
      - MyPlans
      - TrainerTrainees
      - Profile
  SearchTrainers:
    path: ../screens/SearchTrainers
    props:
      screenOptions: *hideHeader
    children:
      - List
      - Filters:
         props:
            options:
              << : [*modal]
  Account:
    path: ../screens/Account
    props:
      screenOptions: *hideHeader
    children:
      - Settings
      # - EditPhotos
      # - EditProfile
      # - EditTrainingPreferences
      # - DeleteAccount
  ActivatedUser:
    export: true
    props:
      screenOptions: *hideHeader
    children:
      - navigator: BottomTabs
      - navigator: Account
      - navigator: SearchTrainers