# yaml-language-server: $schema=../../core/navigation/navigation.schema.json
aliases:
  - &hideHeader
    headerShown: false
  - &lazy
    lazy: true
  - &modal
    presentation: "'modal'"
  - &header
    header: props => <Screen.Header {...props} />
    headerShown: true

navigatorsImports:
  BottomTabBar: ../components

navigators:
  FirstLogin:
    export: true
    lazy: false
    path: ../screens/FirstLogin
    props:
      screenOptions: *hideHeader
    children:
      - ChooseRole
      - Trainee
      - Trainer
  ActivateAccountTrainee:
    export: true
    path: ../screens/ActivateAccount/Trainee
    props:
      screenOptions: *hideHeader
    children:
      - Profile
      - Target
      - Photos
  ActivateAccountTrainer:
    export: true
    path: ../screens/ActivateAccount/Trainer
    props:
      screenOptions: *hideHeader
    children:
      - Profile
      - Contact
      - Offer
      - Photos
  BottomTabs:
    type: bottom-tab
    path: ../screens/BottomTabs
    lazy: false
    props:
      screenOptions:
        << : [*hideHeader, *lazy]
      tabBar: props => <BottomTabBar {...props} />
    children:
      - Home
      - Calendar
      - MyPlans
      - TrainerTrainees
      - Profile
  HomeNavigator:
    path: '../screens/BottomTabs/Home/HomeNavigator'
    export: true
    passParams: true
    props:
      screenOptions: *hideHeader
    children:
      - TrainingList
      - TrainingDetails
      - UpdateParameters:
          props:
            options:
              << : [*modal]
  
  SearchTrainers:
    path: ../screens/SearchTrainers
    props:
      screenOptions: *hideHeader
    children:
      - Home 
      - List
      - ProfileDetails:
          params:
            id: string
            trainerId: string
            name: string
            city: string
            email: string
            phoneNumber: string
            specializations: string[]
            images: string[]
            averageBookingRating: string
      - Availability:
          params:
            trainerId: string
  SearchTrainersListNavigator:
    path: ../screens/SearchTrainers/SearchTrainersListNavigator
    export: true
    passParams: true
    props:
      screenOptions: *hideHeader
    children:
      - List:
          props:
            options:
              << : [*hideHeader]
      - Filters:
          props:
            options:
              << : [*modal]
  SearchTrainersAvailabilityNavigator:
    path: ../screens/SearchTrainers/SearchTrainersAvailabilityNavigator
    export: true
    passParams: true
    props:
      screenOptions: *hideHeader
    children:
      - Monthly
      - Weekly:
          params:
            weekDate: string
      - Reservation:
          params:
            dateTime: string
            traineeId: string
          props:
            options:
              << : [*modal]
          
  CalendarTrainerNavigator:
    path: '../screens/BottomTabs/Calendar/CalendarTrainerNavigator'
    export: true
    passParams: true
    props:
      screenOptions: *hideHeader
    children:
      - Monthly
      - Weekly:
          params:
            weekDate: string
      - AddAvailability:
          props:
            options:
              << : [*modal]
  Account:
    path: ../screens/Account
    props:
      screenOptions: *hideHeader
    children:
      - Settings
      # - EditPhotos
      # - EditProfile
      # - EditTrainingPreferences
      # - DeleteAccount
  ActivatedUser:
    export: true
    props:
      screenOptions: *hideHeader
    children:
      - navigator: BottomTabs
      - navigator: Account
      - navigator: SearchTrainers
      - navigator: ActivateAccountTrainee
      - navigator: ActivateAccountTrainer
      - navigator: FirstLogin