/* eslint-disable @typescript-eslint/no-unsafe-assignment */

/* eslint-disable @typescript-eslint/no-unsafe-return */

/* eslint-disable @typescript-eslint/no-var-requires */
// CAUTION: this file is automatically generated, do not edit it.
export const routeBottomTabsHome = '/bottom-tabs/home';
export const routeBottomTabsCalendar = '/bottom-tabs/calendar';
export const routeBottomTabsMyPlans = '/bottom-tabs/my-plans';
export const routeBottomTabsTrainerTrainees = '/bottom-tabs/trainer-trainees';
export const routeBottomTabsProfile = '/bottom-tabs/profile';
export const routeSearchTrainersList = '/search-trainers/list';
export const routeSearchTrainersFilters = '/search-trainers/filters';
export const routeAccountSettings = '/account/settings';
export const routeBottomTabsNavigator = '/bottom-tabs';
export const routeAccountNavigator = '/account';
export const routeSearchTrainersNavigator = '/search-trainers';
export const toBottomTabsHome = [routeBottomTabsNavigator, routeBottomTabsHome] as unknown as Route;
export const toBottomTabsCalendar = [routeBottomTabsNavigator, routeBottomTabsCalendar] as unknown as Route;
export const toBottomTabsMyPlans = [routeBottomTabsNavigator, routeBottomTabsMyPlans] as unknown as Route;
export const toBottomTabsTrainerTrainees = [
  routeBottomTabsNavigator,
  routeBottomTabsTrainerTrainees,
] as unknown as Route;
export const toBottomTabsProfile = [routeBottomTabsNavigator, routeBottomTabsProfile] as unknown as Route;
export const toSearchTrainersList = [routeSearchTrainersNavigator, routeSearchTrainersList] as unknown as Route;
export const toSearchTrainersFilters = [routeSearchTrainersNavigator, routeSearchTrainersFilters] as unknown as Route;
export const toAccountSettings = [routeAccountNavigator, routeAccountSettings] as unknown as Route;
export const toBottomTabsNavigator = routeBottomTabsNavigator as unknown as Route;
export const toAccountNavigator = routeAccountNavigator as unknown as Route;
export const toSearchTrainersNavigator = routeSearchTrainersNavigator as unknown as Route;
