# yaml-language-server: $schema=../../core/navigation/navigation.schema.json

aliases:
  - &hideHeader
    headerShown: false

navigators:
  FirstLogin:
    export: true
    lazy: false
    props:
      screenOptions: *hideHeader
    path: '../screens'
    children:
      - ChooseRole
      - Trainee
      - Trainer
  ActivateAccountForTraineeNavigator:
    path: ../screens/ActivateAccount/ActivateAccountForTraineeNavigator
    export: true
    passParams: true
    props:
      screenOptions: *hideHeader
    children:
      - Profile
      - Target
      - Photos
  ActivateAccountForTrainerNavigator:
    path: ../screens/ActivateAccount/ActivateAccountForTrainerNavigator
    export: true
    passParams: true
    props:
      screenOptions: *hideHeader
    children:
      - Profile
      - Contact
      - Offer
      - Photos