/* eslint-disable @typescript-eslint/no-unsafe-assignment */

/* eslint-disable @typescript-eslint/no-unsafe-return */

/* eslint-disable @typescript-eslint/no-var-requires */
// CAUTION: this file is automatically generated, do not edit it.
export const routeFirstLoginChooseRole = '/first-login/choose-role';
export const routeFirstLoginTrainee = '/first-login/trainee';
export const routeFirstLoginTrainer = '/first-login/trainer';
export const routeActivateAccountForTraineeProfile = '/activate-account-for-trainee/profile';
export const routeActivateAccountForTraineeTarget = '/activate-account-for-trainee/target';
export const routeActivateAccountForTraineePhotos = '/activate-account-for-trainee/photos';
export const routeActivateAccountForTrainerProfile = '/activate-account-for-trainer/profile';
export const routeActivateAccountForTrainerContact = '/activate-account-for-trainer/contact';
export const routeActivateAccountForTrainerOffer = '/activate-account-for-trainer/offer';
export const routeActivateAccountForTrainerPhotos = '/activate-account-for-trainer/photos';
export const toFirstLoginChooseRole = routeFirstLoginChooseRole as unknown as Route;
export const toFirstLoginTrainee = routeFirstLoginTrainee as unknown as Route;
export const toFirstLoginTrainer = routeFirstLoginTrainer as unknown as Route;
export const toActivateAccountForTraineeProfile = routeActivateAccountForTraineeProfile as unknown as Route;
export const toActivateAccountForTraineeTarget = routeActivateAccountForTraineeTarget as unknown as Route;
export const toActivateAccountForTraineePhotos = routeActivateAccountForTraineePhotos as unknown as Route;
export const toActivateAccountForTrainerProfile = routeActivateAccountForTrainerProfile as unknown as Route;
export const toActivateAccountForTrainerContact = routeActivateAccountForTrainerContact as unknown as Route;
export const toActivateAccountForTrainerOffer = routeActivateAccountForTrainerOffer as unknown as Route;
export const toActivateAccountForTrainerPhotos = routeActivateAccountForTrainerPhotos as unknown as Route;
