/* eslint-disable @typescript-eslint/no-unsafe-assignment */

/* eslint-disable @typescript-eslint/no-unsafe-return */

/* eslint-disable @typescript-eslint/no-var-requires */
// CAUTION: this file is automatically generated, do not edit it.
import * as React from 'react';

import { createNativeStackNavigator } from '@react-navigation/native-stack';

import * as route from './routes';

import { AuthLogin } from '../screens/Login';
import { AuthRegister } from '../screens/Register';
import { AuthWelcome } from '../screens/Welcome';

const AuthNativeStack = createNativeStackNavigator();

export const AuthNavigator = () => {
  return (
    <AuthNativeStack.Navigator
      screenOptions={{
        headerShown: false,
      }}
    >
      <AuthNativeStack.Screen
        name={route.routeAuthWelcome}
        initialParams={{
          meta: {
            presentation: 'card',
          },
        }}
        component={AuthWelcome}
      />
      <AuthNativeStack.Screen
        name={route.routeAuthLogin}
        initialParams={{
          meta: {
            presentation: 'card',
          },
        }}
        component={AuthLogin}
      />
      <AuthNativeStack.Screen
        name={route.routeAuthRegister}
        initialParams={{
          meta: {
            presentation: 'card',
          },
        }}
        component={AuthRegister}
      />
    </AuthNativeStack.Navigator>
  );
};
