# yaml-language-server: $schema=../../core/navigation/navigation.schema.json

aliases:
  - &hideHeader
    headerShown: false

navigators:
  Auth:
    export: true
    lazy: false
    props:
      screenOptions: *hideHeader
    path: '../screens'
    children:
      - Welcome
      - Login
      - Register
      - SentEmail:
         params:
          email: string
      - ActivateAccount:
          params:
           token: string
