/* eslint-disable @typescript-eslint/no-unsafe-assignment */

/* eslint-disable @typescript-eslint/no-unsafe-return */

/* eslint-disable @typescript-eslint/no-var-requires */
// CAUTION: this file is automatically generated, do not edit it.
export const routeAuthWelcome = '/auth/welcome';
export const routeAuthLogin = '/auth/login';
export const routeAuthRegister = '/auth/register';
export const routeAuthSentEmail = '/auth/sent-email';
export const routeAuthActivateAccount = '/auth/activate-account';
export const toAuthWelcome = routeAuthWelcome as unknown as Route;
export const toAuthLogin = routeAuthLogin as unknown as Route;
export const toAuthRegister = routeAuthRegister as unknown as Route;

export const toAuthSentEmail = routeAuthSentEmail as unknown as Route<{
  readonly email: string;
}>;

export const toAuthActivateAccount = routeAuthActivateAccount as unknown as Route<{
  readonly token: string;
}>;
