/* eslint-disable @typescript-eslint/no-unsafe-assignment */

/* eslint-disable @typescript-eslint/no-unsafe-return */

/* eslint-disable @typescript-eslint/no-var-requires */
// CAUTION: this file is automatically generated, do not edit it.
export const routeAuthWelcome = '/auth/welcome';
export const routeAuthLogin = '/auth/login';
export const routeAuthRegister = '/auth/register';
export const toAuthWelcome = routeAuthWelcome as unknown as Route;
export const toAuthLogin = routeAuthLogin as unknown as Route;
export const toAuthRegister = routeAuthRegister as unknown as Route;
