/* eslint-disable @typescript-eslint/no-unsafe-assignment */

/* eslint-disable @typescript-eslint/no-unsafe-return */

/* eslint-disable @typescript-eslint/no-var-requires */
// CAUTION: this file is automatically generated, do not edit it.
export const routeRootAuthorizedNavigator = '/root/authorized-navigator';
export const routeRootNavigator = '/root';
export const toRootAuthorizedNavigator = [routeRootNavigator, routeRootAuthorizedNavigator] as unknown as Route;
export const toRootNavigator = routeRootNavigator as unknown as Route;
